### ISSUE TITLE
Plans for experimental navigator?

### ISSUE THREAD

**Issue by jimthedev** [wix/react-native-controllers#11]
Are there any plans to support the new experimental navigator?

**Comment by talkol** [comment]
This is actually an excellent discussion point and I would like to get feedback here. We're thinking about adding a wrapping layer around react native controllers that adheres to the same interface as the experimental navigator. Generally speaking, declarative API makes more sense in the React/redux world than imperative API like we have now (or the old Navigator/NavigatorIOS have).

My only concern is that declarative API works well for a navigator if you can indeed hold its state externally to the navigator. If this is the case, you would hold your navigation stack in a redux store. The problem with the native navigation controller (iOS UINavigationController) is that it holds its own navigation stack in native code. It's actually important that it will hold its own state, because UINavigationController takes care of a lot of native lifecycle regarding the screens that you push and pop, frees memory when its not needed, etc.

We can't really take this state "out" of UINavigationController. The only thing we could do is duplicate its state and hold duplicate state in redux and then start syncing the two. I'm not sure this is a good practice and it feels like going against the platform. What do you guys think?

Also, if you have a suggestion of how good declarative API should look like, I'm very interesting in seeing it (maybe a github gist).

@ericvicenti
