### ISSUE TITLE
Custom JS object loses type when passing as prop

### ISSUE THREAD

**Issue by Jpoliachik** [wix/react-native-controllers#13]
Passing a JS object between controllers through passProps loses its type through serialization. When using custom JS objects, you end up losing all of the prototype functions associated with the type.

I understand this is a consequence of the bridge, and the best solution is probably to not use custom JS objects at all. However, I ran into this issue trying to convert my project and I felt it was worth a discussion.

**Comment by Jpoliachik** [comment]
Another, even bigger problem concerning passProps just occurred to me. Because functions can't be serialized, there is no way to pass callback functions to controllers. Unless you use a separate system in JS to keep track of all functions being passed around. 

Here's my use case:
A form input requires item selection from a list. Push() list of selectable items. When use selects an item, it should pop() and fill the selected value. 

Is there some way we could keep track of functions passed in as props, then use your `processProperties` function to expose them back as a valid prop within the created element? 

Edit: I took a look, and I don't know if this is possible. Since all controllers are created and passed props using `RCTRootView init` on the ObjC side, I don't know how I could dynamically inject functions back into those props. Let me me know what you think.

**Comment by talkol** [comment]
It's a very good point. You are absolutely right about the reasons behind it, since every component is a new React root wrapped in its own view controller, we have to pass props through native (`RCTRootView init`), which is subject to the serialization limitations of RN.

Let's try to brainstorm a few ideas of how to workaround this, since your use-case is a good one. Some ideas off the top of my head, let me know what you think:
1. I haven't encountered your use-case frequently so far, and I'm trying to think why.. In our apps we rely heavily on redux. Following this architecture decision, we have the standard redux separation between "smart" components and "dumb" components. Smart components are connected to the redux store and are aware of the app state, and dumb components aren't connected - and receive args through props and report back through callbacks. In our mobile apps, we've found that it works nicely to make every screen (the top component held in a React root) a smart component; and make all the sub-components of this screen - dumb components. Smart components rarely receive complex objects through props (since they have access to the store) and rarely report back through prop callbacks (since they dispatch actions). I guess that's why I've never had to pass complex unserializable things through passProps. So one recommendation would be to use redux and pass this info through the store. I've recently posted some [example code](https://github.com/wix/react-native-controllers/issues/9#issuecomment-195217057) on how to do that. I'm also planning to post an entire example project in redux soon.
2. Let's assume we don't want to enforce redux and still find an elegant workaround for your use-case.. Let me think.. The serialization limitation on props for screens never striked me as a major issue because I've seen it in Android activities before, and the ecosystem there seems to deal with this without major problems. Android activities (which are analogous to our screens) are triggered by [Intents](http://developer.android.com/reference/android/content/Intent.html), and these can only contain serializable parameters. The approach they've chosen there for your use-case is to allow activities to [return a result](http://developer.android.com/training/basics/intents/result.html) to the calling activity. We can adopt a similar pattern and support passing results back and forth. The screen making the `push()` or calling the `Modal.showController()` will register a result callback, and the new screen will call a library function to register its result. We will naturally want to make results serializable but that will work nicely in your use-case. Btw - I think `Modal.showController()` makes more sense UX-wise then `push()` in your specific case.
3. Another idea.. The RN bridge supports passing [callbacks](https://facebook.github.io/react-native/docs/native-modules-ios.html#callbacks) because often you would call a native function from JS and you need to receive a return value. These callbacks are bridge-friendly / serialization-friendly so we should be able to adopt a similar mechanism rather easily. We actually already have very similar concepts in the existing implementation - see the way buttons in the nav bar trigger onPress callbacks. We simply follow a registry pattern and register the callbacks using unique string keys. Then pass the key since it's serializable. And when the call back is made, it's made using the string with a library function. Then, we take the response, serialize it, and after passing back through the bridge, we take the callback function from the registry and call it, so the result arrives seamlessly. This would fit nicely inside `processProperties` like you've suggested. So this will allow us to pass callbacks in props. My only concern about this approach is that it's very prone to abuse and incorrect usage.
4. Another important concept for any architecture decision that we make is the concept of _isolation_. I'm sorry for the side-track, but I think you'll find it relevant. After architecting increasingly complex apps in RN, I've come to the conclusion that it's going to be very difficult for big organizations to rely on a single JS bundle (deployment-wise). We are toying with the idea of supporting multiple JS bundles that will run in parallel in the same app on different bridges. Since each bridge comes with its own JS context, these bundles will be executed in complete isolation which brings tremendous dev scale benefits. How is this relevant? because in the future we may find ourselves calling `push()` on a screen that's defined in a different isolated JS context. If we ever want to support that, we'll need to keep API "isolation-ready" - and that's where the serialization limitations start making a lot of sense.

Haha.. this turned out a little longer than I planned. Let me know what you think

**Comment by Jpoliachik** [comment]
Thanks for the detailed response - it is all very helpful! I completely agree with your points about passing serializable data. As long as its made clear to the developer, this isn't an issue. 

I do think there should be a callback mechanism, otherwise the only solution is to use Redux or EventEmitters. Your comment about Android's solution for this is great, and I think it should be emulated! I think it should be possible using the bridge methods you described. 

One additional note: I think there should be a warning or error logged when the user attempts to pass in props that are not serializable. It took me a bit to realize they were getting lost during serialization, so it would be helpful to warn other developers attempting such.

**Comment by talkol** [comment]
I think that the Android result solution will be the best one for now.. I assume it needs to be supported both for show/dismiss modals and push/pop. Originally I thought to add the result to the dismissModal function, but this will not work for the push/pop use-case since the user can click on back at any time. This means a setResult function on the country list screen is probably a better alternative. Every time the user selects a country (a different one can be selected), the setResult will be called and the result will be saved for later. When the screen is dismissed, we will somehow need to call a callback on the parent to let them know what the result is. This means we'll need to hook into some lifecycle event for the dismiss.. maybe will unmount of the country list screen? or maybe add a full fledged lifecycle solution

**Comment by talkol** [comment]
For anyone interested in redux, react-native-navigation is a syntactic sugar wrapper around react-native-controllers which makes working with redux projects very easy.

https://github.com/wix/react-native-navigation/tree/master/example-redux

**Comment by pedro** [comment]
:+1: oof just ran across this.

The way I see `passProps` should take anything React components can define as props, which is why I'm pursuing options 2/3 and not 1/4.

There are great reasons to go for Redux and multiple JS bundles, but I hope we can avoid enforcing these constraints here. I'd love to see this awesome navigation work for apps that don't need either, makes sense?

And +1 to @Jpoliachik, wish whatever serialization is dropping functions would throw an error instead of silently setting them to null. Is that happening somewhere in react-native itself?

Thanks folks!

**Comment by pedro** [comment]
Started writing a patch for this – does anyone know when unsubscribes are called?

I'm probably missing something, but don't see my app unsubscribing to the events registered via `NativeAppEventEmitter.addListener`. I see `_processButtons` and navigation methods like `push` and `resetTo` all return a function to run all unsubscribes, but don't see anything calling it.

Thanks,

**Comment by talkol** [comment]
@pedro regarding unsubscribes, we've just laid out the infra for unsubscribes but they're not being called yet.. we're still considering the correct lifecycle here

**Comment by talkol** [comment]
@Jpoliachik @pedro @artald let's do a quick vote on which way we wanna go here
- Android-style setResult (option 2) will be the easiest and quickest to implement
- passing callbacks (option 3) will probably be best but is significantly more complex due to memory leaks and the fact users will call their callbacks more than once (which RN doesn't support, they have events for this)

**Comment by artald** [comment]
@talkol Option 3 makes sense. Right now, the `Modal.showController` and `Modal.dismissController` APIs even support using Promises (which is probably slightly better than using callbacks). Currently it doesn't return anything as a result but we could create a mechanism which queries the presented/dismissed controllers for it. However, as you said, there is a drawback that you can return a result only once.

I'm not sure why you're saying option 2 is less complex. If we manage our own callback registry instead of using RN callbacks/Promises we'd also end up handling leaks and other issues.

Unless i'm missing something, i'm leaning towards option 3 while accepting the limitation of returning a result once at the end of the action (after a screen was dismissed, after it was popped, etc.).

What do you think?

**Comment by Jpoliachik** [comment]
I agree that option 3 would be best if its implementation doesn't cause any issues. It makes the most sense for developers used to React. While option 2 would be a neat workaround, its a different paradigm.

**Comment by DanielZlotin** [comment]
Closing as not relevant - handled by the new passProps api in Navigation.
