### ISSUE TITLE
Confusing React Native with the Start Up

### ISSUE THREAD

**Issue by mikehuebner** [wix/react-native-controllers#16]
So I brought this up a while ago and while this isn't a true bug, it is a weird occurrence.

Whenever running the startup by calling `ControllerRegistry.setRootController('App');` it runs the app, everything good.

I have a dummy route hooked up to it just to get a view to load, just happens to be the login view (its the only one that works right now) which I call as so: `<NavigationControllerIOS {...routes.login} />` Routes has this:

```
login: {
        id: 'login',
        title: 'Login',
        component: 'Login',
        style: {
            navBarTextColor: '#000',
            navBarBackgroundColor: '#f7f7f7',
            statusBarTextColorScheme: 'dark',
        },
    },
```

I require the Login above, I want to make this conditional to speed up start times. But different issue for a different day.

Checking in the debugger, and because this is the viewed app, React thinks that this is the core of the application. Not the Root element that is being set ('App' in this case).

```
AppRegistry.js:82 Running application "Login" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

Its not causing development troubles, but I am interested as to why this is.

**Comment by talkol** [comment]
As far as I understand, every time RN loads a new RCTRootView with a component inside (`Login` in your case), it displays a console.log with the message you see (Running application "Login" with appParams)

I think they chose the wording of this message poorly, because what they mean is that a new RCTRootView was loaded, but they say that a new app is being run. Since the majority of RN apps have a single RCTRootView, an app === RCTRootView.

In our case this is not true of course because we have several RCTRootViews (one for every screen to be exact).

**Comment by mikehuebner** [comment]
That makes sense, so RN is just under the impression that screen it starts on is the main app. This makes sense. Thanks for clearing that up, didn't know if this was truly an issue or not.
