### ISSUE TITLE
Render Views Under Tab Bar

### ISSUE THREAD

**Issue by PaulBGD** [wix/react-native-controllers#2]
Currently Views aren't rendered under the tab bar, which should be the default.

**Comment by talkol** [comment]
This feature is now fully supported in the style branch with an example
https://github.com/wix/react-native-controllers/tree/style

I'm planning to add a whole bunch of styles, I'll merge the branches when finished

**Comment by talkol** [comment]
Btw, eventually I've decided against making this default because users who are unfamiliar with native iOS might be confused why the top of their view becomes hidden (under the nav bar). You can easily turn this on with a style, and this means you know what you're doing :)

Also, `automaticallyAdjustsScrollViewInsets` doesn't work perfectly on React root views due to child layout events being missed from time to time. I'll need to look into it

**Comment by talkol** [comment]
merged and released under 1.0.4
See https://github.com/wix/react-native-controllers#styling-navigation

**Comment by PaulBGD** [comment]
👍
