### ISSUE TITLE
NavBar is getting pink

### ISSUE THREAD

**Issue by siwymilek** [wix/react-native-controllers#42]
My NavBar is getting pink background if 5 or more NavigationControllers are registered.
It happens only if I set custom NavBar background color (not pink).

**Comment by siwymilek** [comment]
I noticed that my variable with NavBar style is referenced and function processColor processing color on every iteration. I changed my variable with style on function and works well.

```
const navStyle = function () {
    return {
        navBarBackgroundColor: 'rgba(48, 154, 241, 1)',
        navBarButtonColor: 'rgba(255, 255, 255, 1)',
        navBarTextColor: 'rgba(255, 255, 255, 1)'
    };
};
```

**Comment by talkol** [comment]
oh, good catch
The processColors function changes the original object (we need to turn the string color into an int before passing it to native). A better approach would be to clone the object first so we don't change the object that you're passing. I will look into a solution and update this thread.
In the meantime, as a better workaround, you can [clone](https://lodash.com/docs#cloneDeep) the style variable before passing it.

**Comment by talkol** [comment]
Also keep in mind that style colors (background, button and text) are saved between pushes so I think it's enough to set the style once on the root screen. If I remember correctly, there's no need to set it every time.

**Comment by talkol** [comment]
@siwymilek ok, I just committed a fix to master to make sure we don't modify the objects that you're sending as styles. I want you to test it before I release.

So please:
1. pull master of react-native-controllers
2. copy the files manually into your project's node_modules/react-native-controllers folder (since it's unpublished yet)
3. remove any temporary fixes you made for this issue (like the function navStyle)
4. tell me if it fixes the issue :)

Thanks!
