### ISSUE TITLE
Can't set buttons on pushed NavigationController

### ISSUE THREAD

**Issue by siwymilek** [wix/react-native-controllers#43]
Function setRightButtons works only in TabBar components. If I try to push to new controller, buttons don't appear.

```
componentDidMount() {
    const Controllers = require('react-native-controllers');
    const navigationController = Controllers.NavigationControllerIOS("create_expense");
    navigationController.setRightButtons([{
        icon: require('image!save'),
        onPress: function() {
            // code
        }
    }]);
}
```

**Comment by talkol** [comment]
ok, here's what going on:

The native implementation of `setRightButtons` is to set the buttons on the navigation bar's [`topViewController`](https://github.com/wix/react-native-controllers/blob/master/ios/RCCNavigationController.m#L176).

I assume that you're calling `setRightButtons` immediately after the push and that the push has animation. What probably happens is that `topViewController` gets set natively to the new screen only after the animation is over. Since the animation is still playing, this means that you're actually setting the buttons on the screen that called the push, not on the screen that gets pushed.

The best practice in this case is not to use `setRightButtons` at all. To work around the race conditions in this case, we have the `rightButtons` parameter on `navigationController.push()`, see the readme [here](https://github.com/wix/react-native-controllers#navigationcontrollerios).

Only use `setRightButtons` if you need to change the buttons in runtime. For example, if you have a screen that has a disabled button that can turn enabled after the user does something, this would be the way to do it.

Theoretically we can fix the native implementation and cause `setRightButtons` to behave correctly in your case by saving a property with the currently animating view controller, but I don't think that's necessary. I think setting the button on the push is the correct way to go here.

If the thing that worries you is separation of concerns and having the button logic on the pushed screen, I recommend that you switch to `react-native-navigation`. This wrapper library is much simpler to use and actually handles the separation of concerns better by having buttons defined as a `static` variable on the pushed component. Take a look, it's awesome. Internally in Wix, we don't use `react-native-controllers` directly, only through the wrapper.
