### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by mikehuebner** [wix/react-native-controllers#5]
Stupid question kind of, but are there plans to try to support an android version of this as well? If not, won't this ruin some code bases that support both iOS and Android? Or does this already provide a work around for Android?

**Comment by guyca** [comment]
@mikehuebner, your question is actually spot-on. We are currently working on adding support for Android too, hopefully we’ll be able to release an initial version in the upcoming weeks so stay tuned.

**Comment by mikehuebner** [comment]
That is awesome! Thanks for the information!

**Comment by talkol** [comment]
Update regarding our current plans for Android. After some discussion and research, it seems that a direct port of react-native-controllers to Android is not the best approach due to differences between the platforms. We've added another simpler layer of cross-platform abstraction over the navigation API:

https://github.com/wix/react-native-navigation

This abstraction uses react-native-controllers as a dependency.

What we plan to do is implement this abstraction for Android as well. This means if you want Android support and a shared abstract API for both platforms, you should probably be using react-native-navigation. Your life will be simpler too :)

**Comment by mikehuebner** [comment]
I've been looking at that one and was planning on doing a restructure here shortly! 😁 it seems redux would be easier to implement on that API as well.

**Comment by talkol** [comment]
I plan to release a redux flavor of the API in react-native-navigation itself since we're all using it
