### ISSUE TITLE
How to integrate own custom controllers?

### ISSUE THREAD

**Issue by aksonov** [wix/react-native-controllers#78]
Any wiki? As I see i have to implement `initWithProps..` and `performAction..` but also _modify_ code `RCCViewController.controllerWithLayout` ? Looks strange, because it will require fork.

**Comment by aksonov** [comment]
I've added custom controller successfully, but a lot of files were changed, so now i stuck to forked version of this great component. Let me know is there any plans to improve integration.

**Comment by DanielZlotin** [comment]
@aksonov a wiki is on the agenda. Also, this feature is implemented (partially) and we will provide an explanation and examples on how to do it.

As a side note, this is the downside of forks - you can get left behind :wink:

**Comment by artald** [comment]
currently we have a kinda undocumented feature that we use in our project that allows you to add any external view controller as a child view controller.

You can use it when pushing or showing a modal, for example, by specifying your native class name and optional props that you want to pass to it:

```
externalNativeScreenClass: 'MyViewController',
externalNativeScreenProps: {}
```

The downside to this approach is that you still need a React component for this screen because it is added to an existing `RCCViewController`, meaning the external native view-controller "takes over" this component. So effectively the React component `render` does nothing since you can't actually see it.. but other logic like that communicates with your external screen (the RN native interface between this screen and your component) can still go there.

You can see an example for this feature using `react-native-navigation` here: https://github.com/wix/react-native-wordpress-editor

**Comment by artald** [comment]
After the merge with `react-native-navigation` we nee to make sure parity with Android. See here: https://github.com/wix/react-native-navigation/issues/235
