### ISSUE TITLE
How To: Integrate Redux <Provider> into the mix?

### ISSUE THREAD

**Issue by mikehuebner** [wix/react-native-controllers#9]
Hello again!

I'm experimenting with this and just reworked most of the code base I was working with to work around the ViewControllers as in order to run the view controller needs to be the base class, it doesn't run otherwise. In fact it thinks I'm running my 'Login' controller from the dev console:
![image](https://cloud.githubusercontent.com/assets/6125123/13665413/3764dae6-e661-11e5-8b6e-d864ab224a6c.png)

That is besides the point, but I'm trying to wrap the `DrawControllerIOS` property with Redux to keep that moving, is this possible? It just gives me script error if I try to run it otherwise and I can't seem to figure out how to debug this situation. Any information on this would be awesome. Thanks!

**Comment by talkol** [comment]
We are working internally with redux, I'll post some examples soon

**Comment by mikehuebner** [comment]
@talkol Awesome, excited to check it out!

**Comment by talkol** [comment]
I took some of our existing redux code and removed all the irrelevant parts. I didn't check if it's running, but I hope it will give you an idea of how we structure an app based on react-native-controllers + redux.

[`index.ios.js`](https://gist.github.com/talkol/767ea2348253b0654d2a)

[`app.ios.js`](https://gist.github.com/talkol/0f9a73dacbb537afed0b)

[`ExampleScreen.ios.js`](https://gist.github.com/talkol/57141159a1f154d8c073)

Regarding the Login issue that you've included a screenshot.. I'm not quite sure what's the problem is. Can you post some example code? I think it should go in a separate issue though :)

**Comment by mikehuebner** [comment]
So to understand this, each ViewController (basically) has to have its own provider wrapper? No way to just wrap the outside app in a provider and then all contents within that all have those properties like a regular app? If so, no big deal, I just have an idea on how to create a good structure for this if that is the case and I'll be sharing that pretty soon here.

Also, ES6 class syntax, is that a soon to come thing (reading the comments in the code posted)? Because right now createClass is the only way to wrap the components and if thats going to be the case it's not a big deal because it's generally in 1 part of the app anyway. Doesn't break too much structure.

**Comment by talkol** [comment]
You have to pass your store to each screen component separately. The reason is that each screen is actually a separate React root. What Provider does is set the store in the React context, but context is only shared with child components. Since your screens are not children of each other (they are sibling React roots) - you must pass the store separately to each of them.

You can do it by wrapping each one with a Provider. And you can also pass the store in a prop named `store` instead. The Provider method will make the store available automatically to smart connected child components, so I recommend this method.

Regarding the ES6 syntax in the controller area, I'm planning to ditch the `hijackReact` hack altogether. When it's done, we can make this part ES6 as well..

**Comment by mikehuebner** [comment]
Awesome to hear, and makes sense. I got some restructuring to do.

In regards to the other issue I was having with React Native saying login was the root, you answered why thats happening with this. The instantiated class the `AppRegister` was running was the Login to register the component to the controller. React thought that was the root, not the actual Root container I had set up since I can't set that to be the source of everything (sets up my general environment, redux and all) I'll just refactor it to fit the needs of what this is doing. Thanks for that information. If you're still concerned about this issue I'll show some code to recreate it and we will get another issue going.

**Comment by talkol** [comment]
Internally in Wix, we rely on react-native-controllers in our apps, but we don't use it directly. Instead, we've made a very simple wrapper that makes using it much easier. I think it's a good idea to make an open source release of this wrapper and you will find it beneficial. Since react-native-controllers is a relatively low-level library, a higher abstraction over it will definitely make it more usable.

I'll make sure to include 2 example projects when I open source the wrapper. One without redux and one with. I think redux is becoming the de facto standard for complex React apps, so we'll give it special attention.

**Comment by mikehuebner** [comment]
When might this be released? I'm really curious to see your guys solution vs mine, mine is getting kinda messy 😅

**Comment by Jpoliachik** [comment]
I am interested in seeing this as well, since I will probably be using Redux soon.

**Comment by talkol** [comment]
Here it is:
https://github.com/wix/react-native-navigation
It's still work in progress and the redux example isn't there yet, but hopefully I'll add it tomorrow
Take a look at the regular example there and see how the usage is significantly simplified :)

**Comment by talkol** [comment]
Redux support is here! react-native-navigation now fully supports redux. The API is actually now even simpler and more concise.

A best practice redux example:
https://github.com/wix/react-native-navigation/tree/master/example-redux

Release notes for the new version:
https://github.com/wix/react-native-navigation/blob/master/RELEASES.md
